// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Docs {
  created: string;
  last_updated: string | null;
  filetype: string | null;
  version: number;
  size: bigint;
  data: Array<number> | null;
}
