[package]
name = "mugen-ui"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wee_alloc = "0.4"
yew = "0.19"
yew-router = "0.16"
