debug:
	wasm-pack build --debug --no-typescript -d ../target/pkg/debug --out-name mugen_ui --target web
release:
	wasm-pack build --release --no-typescript -d ../target/pkg/release --out-name mugen_ui --target web
