[package]
name = "mugen-server"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
axum = "0.4.5"
dotenv = "0.15.0"
tokio = { version = "1.16.1", features = ["full"] }
tokio-util = "0.6.9"
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }
tower = { version = "0.4.11", features = ["timeout"] }
tower-http = { version = "0.2.1", features = ["fs", "trace"] }
serde = { version = "1.0.136", features = ["derive"] }
sea-orm = { version = "0.5.0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"], default-features = false }
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive", "env"] }
