[package]
name = "mugen-server"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2018"

[dependencies]
axum = "0.4.4"
dotenv = "0.15.0"
tokio = { version = "1.15.0", features = ["full"] }
tokio-util = "0.6.9"
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
tower = { version = "0.4.11", features = ["full"] }
tower-http = { version = "0.2.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

