[package]
name = "mugen-server"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
axum = "0.5.4"
dotenv = "0.15.0"
tokio = { version = "1.18.0", features = ["full"] }
tokio-util = "0.7.1"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tower = { version = "0.4.12", features = ["timeout"] }
tower-http = { version = "0.3.2", features = ["fs", "trace"] }
serde = { version = "1.0.136", features = ["derive"] }
sea-orm = { version = "0.7.1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-json",
    "with-chrono",
], default-features = false }
anyhow = "1.0.57"
clap = { version = "3.1.13", features = ["derive", "env"] }
entity = { path = "entity" }
migration = { path = "migration" }
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter", "json", "fmt", "registry"] }
tracing-attributes = "0.1.19"
tracing-appender = "0.2.0"
toml = "0.5.8"

[features]
yew-frontend = []
