[package]
name = "mugen-server"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.10"
rocket_codegen = "0.4.10"
rocket_contrib = "0.4.10"
argon2 = "0.2.1"
bcrypt = "0.10"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "2.33.3"
diesel = { version = "1.4.6", features = ["postgres", "extras"] }
dotenv = "0.15.0"
env_logger = "0.8.3"
lazy_static = "1.4.0"
log = "0.4.14"
r2d2 = "0.8.9"
r2d2_postgres = "0.18.0"
serde = { version = "1.0.126", features = ["derive"] }
tokio = "1.5.0"
