 # general logging (std out)
[logging]
format = "pretty" # Options: `full`, `compact`, `pretty` and `json`
modules = [
    "mugen_server=debug",
    "tower_http=debug",
]

# logging to files
[[file-logger]]
enabled = true
name = "db"
path = "./database.json"
format = "json" # Options: `full`, `compact`, `pretty` and `json`
modules = [
    "mugen_server::config::db=debug",
]

[[file-logger]]
enabled = true
name = "request"
path = "./requests.log"
format = "compact" # Options: `full`, `compact`, `pretty` and `json`
modules = [
    "mugen_server::handler=info",
]
