[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "debug"
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 1337
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }
