version: "3.8"
services:
  mugendb:
    environment:
      - POSTGRES_USER=mugen
      - POSTGRES_PASSWORD=mugen
      - POSTGRES_DB=mugendb
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:

