version: "3.8"
services:
    mugendb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=mugen
            - POSTGRES_PASSWORD=mugen
            - POSTGRES_DB=mugendb
